apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - config/
  - storage/
  - services/
  - deployments/
  - ingress/

namespace: ecommerce

commonLabels:
  app.kubernetes.io/part-of: ecommerce-microservices
