---
apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-server-config
data:
  SERVER_PORT: "8761"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: "TRACE"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka"
  SERVER_PORT: "8080"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: "http://keycloak:8080/realms/spring-boot-microservices-realm"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
data:
  SPRING_DATA_MONGODB_URI: "mongodb://mongo:27017/product-service"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
  SERVER_PORT: "8080"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-order:3306/order_service?allowPublicKeyRetrieval=true&useSSL=false"
  SPRING_DATASOURCE_USERNAME: "ibatulanand"
  SERVER_PORT: "8080"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
  SPRING_KAFKA_BOOTSTRAPSERVERS: "kafka:9092"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-inventory:3306/inventory_service?allowPublicKeyRetrieval=true&useSSL=false"
  SPRING_DATASOURCE_USERNAME: "ibatulanand"
  SERVER_PORT: "8080"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  SERVER_PORT: "8080"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  NEXT_PUBLIC_API_URL: "http://api-gateway:8080"
  NEXTAUTH_URL: "http://frontend:3000"
  KEYCLOAK_CLIENT_ID: "spring-cloud-client"
  KEYCLOAK_ISSUER: "http://keycloak:8080/realms/spring-boot-microservices-realm"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'product-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['product-service:8080']
      
      - job_name: 'order-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['order-service:8080']
      
      - job_name: 'inventory-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['inventory-service:8080']
      
      - job_name: 'notification-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['notification-service:8080']
