apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ecommerce-trigger-template
spec:
  params:
    - name: gitrepositoryurl
      description: The git repository url
    - name: gitrevision
      description: The git revision
      default: main
    - name: namespace
      description: The namespace to deploy to
      default: ecommerce-dev
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: ci-cd-pipeline-run-
        namespace: $(tt.params.namespace)
      spec:
        pipelineRef:
          name: ci-cd-pipeline
        params:
          - name: git-url
            value: $(tt.params.gitrepositoryurl)
          - name: git-revision
            value: $(tt.params.gitrevision)
          - name: namespace
            value: $(tt.params.namespace)
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: tekton-workspace-pvc
          - name: maven-settings
            configMap:
              name: maven-settings
