---
apiVersion: v1
kind: Service
metadata:
  name: mysql-order
  labels:
    app: mysql-order
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql-order
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-inventory
  labels:
    app: mysql-inventory
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql-inventory
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-mysql
  labels:
    app: keycloak-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: keycloak-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
      name: external
    - port: 29092
      targetPort: 29092
      name: internal
  selector:
    app: kafka
