apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-pipeline
spec:
  workspaces:
    - name: shared-workspace
      description: The workspace containing the source code
  params:
    - name: git-url
      type: string
      description: URL of the Git repository
    - name: git-revision
      type: string
      description: Git revision to checkout
      default: "main"
    - name: manifest-dir
      type: string
      description: Directory containing Kubernetes manifests
      default: "kubernetes-manifests"
    - name: overlay
      type: string
      description: Kustomize overlay to use
      default: "overlays/dev"
    - name: namespace
      type: string
      description: Namespace to deploy to
      default: "ecommerce-dev"
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: subdirectory
          value: ""
    
    - name: deploy
      taskRef:
        name: deploy-to-openshift
      runAfter:
        - fetch-source
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: MANIFEST_DIR
          value: $(params.manifest-dir)
        - name: OVERLAY
          value: $(params.overlay)
        - name: NAMESPACE
          value: $(params.namespace)
