apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: frontend-build-pipeline
spec:
  workspaces:
    - name: shared-workspace
      description: The workspace containing the source code
  params:
    - name: git-url
      type: string
      description: URL of the Git repository
    - name: git-revision
      type: string
      description: Git revision to checkout
      default: "main"
    - name: image-name
      type: string
      description: Name of the image to build
    - name: context-dir
      type: string
      description: The context directory within the source
      default: "frontend"
    - name: npm-install-command
      type: string
      description: NPM install command
      default: "npm install"
    - name: npm-build-command
      type: string
      description: NPM build command
      default: "npm run build"
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: subdirectory
          value: ""
    
    - name: npm-build
      taskRef:
        name: npm-build
      runAfter:
        - fetch-source
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: CONTEXT_DIR
          value: $(params.context-dir)
        - name: INSTALL_COMMAND
          value: $(params.npm-install-command)
        - name: BUILD_COMMAND
          value: $(params.npm-build-command)
    
    - name: build-image
      taskRef:
        name: buildah
      runAfter:
        - npm-build
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: $(params.image-name)
        - name: CONTEXT_DIR
          value: $(params.context-dir)
        - name: DOCKERFILE
          value: "Dockerfile"
