name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      working-directory: ./frontend
      run: npm install
    
    - name: Build Next.js app
      working-directory: ./frontend
      run: npm run build
    
    - name: Build the Docker image
      run: docker build . --file frontend/Dockerfile --tag my-image-name:$(date +%s)
